import { createActions } from 'redux-actions';

export default createActions(
  'INIT_ASYNCLATEST',
  'REDUCER_CHANGE',

  'VIEW_CHANGE',
  'CHANGE_TEXT_ASYNCLATEST',
  'SELECT_LEGEND_ASYNCLATEST',

  'READFILE_ASYNCLATEST',
  'SAVEFILE_ASYNCLATEST',

  'PREVIEW_CHANGE',
  'PAGE_CHANGE',
  'SYNC_HTML_ASYNCLATEST'
);
